# Generated by Django 2.1.5 on 2019-11-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkScheduleWeb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='class_id',
        ),
    ]
