# Generated by Django 2.1 on 2019-10-28 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeworkScheduleWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_type',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeworkScheduleWeb.Class'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeworkScheduleWeb.Class'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.DeleteModel(
            name='ClassCategory',
        ),
    ]
