# Generated by Django 2.1.5 on 2019-11-04 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkScheduleWeb', '0003_auto_20191104_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='assignment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='homeworkScheduleWeb.Assignment'),
        ),
    ]
